{{/*
ConfigMap for generating default environment variables for the app
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frank-console.fullname" . }}-env
  labels:
    {{- include "frank-console.labels" . | nindent 4 }}
data:
  management.gateway.outbound.class: "org.frankframework.management.gateway.HazelcastOutboundGateway"
  hazelcast.network.file: "/app/hazelcast-network.xml"
  # Reverse proxy/ingress should be used for https
  application.security.http.transportGuarantee: "NONE"
  TZ: "{{ .Values.timeZone }}"
  container.image: "{{ .Values.image.registry }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  helm.release.version: "{{ .Chart.Version }}"
  {{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: "{{ $value }}"
  {{- end -}}