apiVersion: apps/v1
kind: Deployment
{{ template "frank-console.metadata" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frank-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frank-console.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap.env: {{ include (print $.Template.BasePath "/configmap.env.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "frank-console.serviceAccountName" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        -
          {{- include "frank-console.container" . | nindent 10 }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ template "frank-console.fullname" . }}-hazelcast-network
          configMap:
            name: {{ .Release.Name }}-hazelcast-network
        {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: tmpfs
          emptyDir: { }
        {{- end }}
        {{- range .Values.generateConfigMap }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
            optional: {{ .optional | default false }}
            defaultMode: {{ .defaultMode | default 0644 }}
            {{- with .items }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- range .Values.generateSecret }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
            defaultMode: {{ .defaultMode | default 0644 }}
            optional: {{ .optional | default false }}
            {{- with .items }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
