{{/*
ConfigMap for generating default environment variables for the app
*/}}
{{- $dtapStage := .Values.application.dtap.stage | required "The DTAP stage is a required value. Ref: https://frank-manual.readthedocs.io/en/latest/deploying/dtapAndProperties.html" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frankframework.fullname" . }}-env
  labels:
    {{- include "frankframework.labels" . | nindent 4 }}
data:
  {{- if .Values.console.enabled }}
  management.gateway.inbound.class: "org.frankframework.management.gateway.HazelcastInboundGateway"
  hazelcast.network.file: "/usr/local/tomcat/lib/hazelcast-network.xml"
  {{- end }}
  # Reverse proxy/ingress should be used for https
  application.security.http.transportGuarantee: "NONE"
  TZ: "{{ .Values.timeZone }}"
  instance.name: "{{ include "frankframework.instance.name" . }}"
  container.image: "{{ .Values.image.registry }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  ADDITIONAL.PROPERTIES.FILE: "DeploymentSpecifics.properties,BuildInfo.properties,ServerSpecifics_${application.server.type}${application.server.type.custom}.properties,SideSpecifics_${dtap.side}.properties,StageSpecifics_${dtap.stage}.properties,K8sSpecifics.yaml,Test.properties"
  helm.release.version: "{{ .Chart.Version }}"
  {{- with .Values.application }}
  dtap.side: "{{ .dtap.side | default $.Release.Namespace }}"
  dtap.stage: "{{ $dtapStage }}"
  {{- with .configurations.names }}
  configurations.names: "{{ join "," . }}"
  {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: "{{ $value }}"
  {{- end -}}