{{- range .Values.generateSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "frankframework.labels" $ | nindent 4 }}
type: {{ .type }}
{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- if .stringData }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
---
{{- end -}}