apiVersion: v2
name: frankframework
description: A Helm chart for running the Frank!Framework on Kubernetes
version: 0.2.17
appVersion: "7.8"
type: application
home: https://frankframework.org
icon: https://raw.githubusercontent.com/frankframework/charts/master/charts/frankframework/icon.svg

dependencies:
  - name: ff-common
    version: ~0.1.23
    repository: file://../ff-common
