{{- template "ff-common.configmap" (list . "ff-common.configmap.env") -}}
{{- define "ff-common.configmap.env" -}}
metadata:
  name: {{ template "ff-common.fullname" . }}-env
data:
  # Enable Narayana transaction manager
  application.server.type.custom: NARAYANA
  JAVA_OPTS: -Xmx{{ .Values.frank.memory }} -Xms{{ .Values.frank.memory }}
  TZ: {{ .Values.timeZone }}
  instance.name: {{ .Values.frank.instance.name | default (include "ff-common.fullname" .) }}
  dtap.stage: {{ .Values.frank.dtap.stage }}
  dtap.side: {{ .Values.frank.dtap.side | default "cluster" }}
  {{- with .Values.frank.configurations.names }}
  configurations.names: {{ . }}
  {{- end }}
  application.security.http.authentication: "{{ .Values.frank.security.http.authentication }}"
{{/*  application.security.http.transportGuarantee: {{ .Values.frank.security.http.enforceHttps | ternary "CONFIDENTIAL" "NONE" }}*/}}
  {{- if .Values.frank.security.http.authentication }}
  {{- with .Values.frank.security.http.ad }}
  application.security.http.authenticators: AdAuthenticator
  application.security.http.authenticators.AdAuthenticator.type: AD
  application.security.http.authenticators.AdAuthenticator.baseDn: {{ .baseDn }}
  application.security.http.authenticators.AdAuthenticator.url: {{ .url }}
  servlet.IAF-API.authenticator: AdAuthenticator
  {{- end }}
  {{- end }}
  {{- if .Values.frank.credentials }}
{{/*  credentialFactory.class: nl.nn.credentialprovider.FileSystemCredentialFactory*/}}
  credentialFactory.class: nl.nn.credentialprovider.PropertyFileCredentialFactory
  credentialFactory.map.properties: /opt/frank/secrets/{{.Values.frank.credentials.key}}
  {{- end }}
  {{- if .Values.frank.properties }}
  {{ .Values.frank.properties | toYaml }}
  {{- end }}
{{- end -}}