apiVersion: v2
appVersion: "7.8"
description: A Helm chart for running the Frank!Framework on Kubernetes
name: frank-framework
icon: https://raw.githubusercontent.com/ibissource/charts/ff-common/charts/frank-framework/icon.svg
type: application
version: 0.2.0

dependencies:
  - name: ff-common
    version: 0.1.0
    repository: file://../ff-common
