# Default values for ff-commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: 'nexus.frankframework.org/frank-framework'
  tag: '7.8'
  pullPolicy: ''

securityContext:
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 80



timeZone: Europe/Amsterdam

frank:
  memory: 4G
  dtap:
    stage: LOC
  credentials: {}
  instance:
    name: "z"
  configurations:
    names: ''
  security:
    http:
      authentication: true
      ad: {}


