## @section Frank!Framework parameters
## @descriptionStart
## This chart is a wrapper for the Frank!Framework chart.
## See the documentation for the Frank!Framework chart for more information.
## @descriptionEnd

frankframework:
  ## @param frankframework.image.registry frank2example image registry
  ## @param frankframework.image.repository frank2example image repository
  ## @param frankframework.image.tag frank2example image tag (immutable tags are recommended)
  ## @param frankframework.image.pullPolicy frank2example image pull policy
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  ## @param frankframework.image.pullSecrets frank2example image pull secrets
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - name: myRegistryKeySecretName
  ##
  image:
    registry: nexus.frankframework.org
    repository: ff-test
    tag: "9.0.0-SNAPSHOT-tomcat"
    pullPolicy: Always
    pullSecrets: []

  application:
    ## @param frankframework.application.dtap.stage DTAP stage can't be changed for this application.
    ##
    dtap:
      stage: LOC
    ## @param frankframework.application.instance.name Instance name can't be changed for this application.
    instance:
      name: Ibis4Test

  ## @skip frankframework.environmentVariables
  ##
  environmentVariables:
    jdbc.dbms.default: 'h2'
    jms.provider.default: ''

  ## @extra frankframework.startupProbe Configure the startup probe
  ## @extra frankframework.startupProbe ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
  ## @param frankframework.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param frankframework.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param frankframework.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param frankframework.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param frankframework.startupProbe.successThreshold Success threshold for startupProbe
  ## @param frankframework.startupProbe.httpGet.path Path for startupProbe
  ## @param frankframework.startupProbe.httpGet.port Port for startupProbe
  ##
  startupProbe:
    initialDelaySeconds: 40
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 12
    successThreshold: 1
    httpGet:
      path: /iaf-test/iaf/api/server/health
      port: 8080

  ## @extra frankframework.livenessProbe Configure the liveness probe
  ## @extra frankframework.livenessProbe ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
  ## @param frankframework.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param frankframework.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param frankframework.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param frankframework.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param frankframework.livenessProbe.successThreshold Success threshold for livenessProbe
  ## @param frankframework.livenessProbe.httpGet.path Path for livenessProbe
  ## @param frankframework.livenessProbe.httpGet.port Port for livenessProbe
  ##
  livenessProbe:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 12
    successThreshold: 1
    httpGet:
      path: /iaf-test/iaf/api/server/health
      port: 8080

  ## @extra frankframework.readinessProbe Configure the readiness probe
  ## @extra frankframework.readinessProbe ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
  ## @param frankframework.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param frankframework.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param frankframework.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param frankframework.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param frankframework.readinessProbe.successThreshold Success threshold for readinessProbe
  ## @param frankframework.readinessProbe.httpGet.path Path for readinessProbe
  ## @param frankframework.readinessProbe.httpGet.port Port for readinessProbe
  ##
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    httpGet:
      path: /iaf-test/iaf/api/server/health
      port: 8080